version: 1

steps:
  ## step 1 (and only) - run tests
  - name: build
    image: silex/emacs:27
    ruleset:
      branch: [ main ]
      event: push
    commands:
      # wanted to use make, but this image does not have make
      - emacs --script ./woozietest.el

